// apps/app-react/src/App.tsx
import "./assets/main.css";
import { memo, useReducer } from "react";

const random = (max: number) => Math.round(Math.random() * 1000) % max;

const A = [
  "pretty",
  "large",
  "big",
  "small",
  "tall",
  "short",
  "long",
  "handsome",
  "plain",
  "quaint",
  "clean",
  "elegant",
  "easy",
  "angry",
  "crazy",
  "helpful",
  "mushy",
  "odd",
  "unsightly",
  "adorable",
  "important",
  "inexpensive",
  "cheap",
  "expensive",
  "fancy",
];
const C = [
  "red",
  "yellow",
  "blue",
  "green",
  "pink",
  "brown",
  "purple",
  "brown",
  "white",
  "black",
  "orange",
];
const N = [
  "table",
  "chair",
  "house",
  "bbq",
  "desk",
  "car",
  "pony",
  "cookie",
  "sandwich",
  "burger",
  "pizza",
  "mouse",
  "keyboard",
];

let nextId = 1;

const buildData = (count: number) => {
  const data = new Array(count);

  for (let i = 0; i < count; i++) {
    data[i] = {
      id: nextId++,
      label: `${A[random(A.length)]} ${C[random(C.length)]} ${N[random(N.length)]}`,
    };
  }

  return data;
};

const initialState = { data: [], selected: 0 };

const listReducer = (state, action) => {
  const { data, selected } = state;

  switch (action.type) {
    case "RUN":
      return { data: buildData(1000), selected: 0 };
    case "RUN_LOTS":
      return { data: buildData(10000), selected: 0 };
    case "ADD":
      return { data: data.concat(buildData(1000)), selected };
    case "UPDATE": {
      const newData = data.slice(0);

      for (let i = 0; i < newData.length; i += 10) {
        const r = newData[i];

        newData[i] = { id: r.id, label: r.label + " !!!" };
      }

      return { data: newData, selected };
    }
    case "CLEAR":
      return { data: [], selected: 0 };
    case "SWAP_ROWS":
      const newdata = [...data];
      if (data.length > 998) {
        const d1 = newdata[1];
        const d998 = newdata[998];
        newdata[1] = d998;
        newdata[998] = d1;
      }
      return { data: newdata, selected };
    case "REMOVE": {
      return { data: data.filter((d) => d.id !== action.id), selected };
    }
    case "SELECT":
      return { data, selected: action.id };
    default:
      return state;
  }
};

type RowProps = {
  selected: boolean;
  item: { id: number; label: string };
  dispatch: (action: { type: string; id?: number }) => void;
};

const Row = memo(
  ({ selected, item, dispatch }: RowProps) => (
    <tr className={selected ? "danger" : ""}>
      <td className="col-md-1">{item.id}</td>
      <td className="col-md-4">
        <a onClick={() => dispatch({ type: "SELECT", id: item.id })}>
          {item.label}
        </a>
      </td>
      <td className="col-md-1">
        <a onClick={() => dispatch({ type: "REMOVE", id: item.id })}>
          <span className="glyphicon glyphicon-remove" aria-hidden="true" />
        </a>
      </td>
      <td className="col-md-6" />
    </tr>
  ),
  (prevProps, nextProps) =>
    prevProps.selected === nextProps.selected &&
    prevProps.item === nextProps.item,
);

const Button = ({ id, cb, title }) => (
  <div className="col-sm-6 smallpad">
    <button
      type="button"
      className="btn btn-primary btn-block"
      id={id}
      onClick={cb}
    >
      {title}
    </button>
  </div>
);

const Jumbotron = memo(
  ({ dispatch }) => (
    <div className="jumbotron">
      <div className="row">
        <div className="col-md-6">
          <h1>React App</h1>
        </div>
        <div className="col-md-6">
          <div className="row">
            <Button
              id="run"
              title="Create 1,000 rows"
              cb={() => dispatch({ type: "RUN" })}
            />
            <Button
              id="runlots"
              title="Create 10,000 rows"
              cb={() => dispatch({ type: "RUN_LOTS" })}
            />
            <Button
              id="add"
              title="Append 1,000 rows"
              cb={() => dispatch({ type: "ADD" })}
            />
            <Button
              id="update"
              title="Update every 10th row"
              cb={() => dispatch({ type: "UPDATE" })}
            />
            <Button
              id="clear"
              title="Clear"
              cb={() => dispatch({ type: "CLEAR" })}
            />
            <Button
              id="swaprows"
              title="Swap Rows"
              cb={() => dispatch({ type: "SWAP_ROWS" })}
            />
          </div>
        </div>
      </div>
    </div>
  ),
  () => true,
);

export const App = () => {
  const [{ data, selected }, dispatch] = useReducer(listReducer, initialState);

  return (
    <div className="container">
      <Jumbotron dispatch={dispatch} />
      <table className="table table-hover table-striped test-data">
        <tbody>
          {data.map((item) => (
            <Row
              key={item.id}
              item={item}
              selected={selected === item.id}
              dispatch={dispatch}
            />
          ))}
        </tbody>
      </table>
      <span
        className="preloadicon glyphicon glyphicon-remove"
        aria-hidden="true"
      />
    </div>
  );
};

// apps/app-angular/src/app/app.component.ts
import { Component } from "@angular/core";
import { NgFor } from "@angular/common";

interface Data {
  id: number;
  label: string;
}

const adjectives = [
  "pretty",
  "large",
  "big",
  "small",
  "tall",
  "short",
  "long",
  "handsome",
  "plain",
  "quaint",
  "clean",
  "elegant",
  "easy",
  "angry",
  "crazy",
  "helpful",
  "mushy",
  "odd",
  "unsightly",
  "adorable",
  "important",
  "inexpensive",
  "cheap",
  "expensive",
  "fancy",
];
const colours = [
  "red",
  "yellow",
  "blue",
  "green",
  "pink",
  "brown",
  "purple",
  "brown",
  "white",
  "black",
  "orange",
];
const nouns = [
  "table",
  "chair",
  "house",
  "bbq",
  "desk",
  "car",
  "pony",
  "cookie",
  "sandwich",
  "burger",
  "pizza",
  "mouse",
  "keyboard",
];

@Component({
  selector: "app-root",
  standalone: true,
  imports: [NgFor],
  template: `
    <div class="container">
      <div class="jumbotron">
        <div class="row">
          <div class="col-md-6">
            <h1>Angular App</h1>
          </div>
          <div class="col-md-6">
            <div class="col-sm-6 smallpad">
              <button
                type="button"
                class="btn btn-primary btn-block"
                id="run"
                (click)="run()"
                ref="text"
              >
                Create 1,000 rows
              </button>
            </div>
            <div class="col-sm-6 smallpad">
              <button
                type="button"
                class="btn btn-primary btn-block"
                id="runlots"
                (click)="runLots()"
              >
                Create 10,000 rows
              </button>
            </div>
            <div class="col-sm-6 smallpad">
              <button
                type="button"
                class="btn btn-primary btn-block"
                id="add"
                (click)="add()"
                ref="text"
              >
                Append 1,000 rows
              </button>
            </div>
            <div class="col-sm-6 smallpad">
              <button
                type="button"
                class="btn btn-primary btn-block"
                id="update"
                (click)="update()"
              >
                Update every 10th row
              </button>
            </div>
            <div class="col-sm-6 smallpad">
              <button
                type="button"
                class="btn btn-primary btn-block"
                id="clear"
                (click)="clear()"
              >
                Clear
              </button>
            </div>
            <div class="col-sm-6 smallpad">
              <button
                type="button"
                class="btn btn-primary btn-block"
                id="swaprows"
                (click)="swapRows()"
              >
                Swap Rows
              </button>
            </div>
          </div>
        </div>
      </div>
      <table class="table table-hover table-striped test-data">
        <tbody>
          @for (item of data; track item.id) {
            <tr [class.danger]="item.id === selected">
              <td class="col-md-1">{{ item.id }}</td>
              <td class="col-md-4">
                <a href="#" (click)="select(item, $event)">{{ item.label }}</a>
              </td>
              <td class="col-md-1">
                <a href="#" (click)="delete(item, $event)"
                  ><span
                    class="glyphicon glyphicon-remove"
                    aria-hidden="true"
                  ></span
                ></a>
              </td>
              <td class="col-md-6"></td>
            </tr>
          }
        </tbody>
      </table>
      <span
        class="preloadicon glyphicon glyphicon-remove"
        aria-hidden="true"
      ></span>
    </div>
  `,
  styles: [],
})
export class AppComponent {
  data: Array<Data> = [];
  selected?: number = undefined;
  id: number = 1;
  backup?: Array<Data> = undefined;

  buildData(count: number = 1000): Array<Data> {
    var data: Array<Data> = new Array(count);
    for (var i = 0; i < count; i++) {
      data[i] = {
        id: this.id,
        label: `${adjectives[this._random(adjectives.length)]} ${colours[this._random(colours.length)]} ${nouns[this._random(nouns.length)]}`,
      };
      this.id++;
    }
    return data;
  }

  _random(max: number) {
    return Math.round(Math.random() * 1000) % max;
  }

  itemById(index: number, item: Data) {
    return item.id;
  }

  select(item: Data, event: Event) {
    event.preventDefault();
    this.selected = item.id;
  }

  delete(item: Data, event: Event) {
    event.preventDefault();
    for (let i = 0, l = this.data.length; i < l; i++) {
      if (this.data[i].id === item.id) {
        this.data.splice(i, 1);
        break;
      }
    }
  }

  run() {
    this.data = this.buildData();
  }

  add() {
    this.data = this.data.concat(this.buildData(1000));
  }

  update() {
    for (let i = 0; i < this.data.length; i += 10) {
      this.data[i].label += " !!!";
    }
  }
  runLots() {
    this.data = this.buildData(10000);
    this.selected = undefined;
  }
  clear() {
    this.data = [];
    this.selected = undefined;
  }
  swapRows() {
    if (this.data.length > 998) {
      var a = this.data[1];
      this.data[1] = this.data[998];
      this.data[998] = a;
    }
  }
}

<div class="container">
  <div class="jumbotron">
    <div class="row">
      <div class="col-md-6">
        <h1>Angular App</h1>
      </div>
      <div class="col-md-6">
        <div class="col-sm-6 smallpad">
          <button
            type="button"
            class="btn btn-primary btn-block"
            id="run"
            (click)="run()"
            ref="text"
          >
            Create 1,000 rows
          </button>
        </div>
        <div class="col-sm-6 smallpad">
          <button
            type="button"
            class="btn btn-primary btn-block"
            id="runlots"
            (click)="runLots()"
          >
            Create 10,000 rows
          </button>
        </div>
        <div class="col-sm-6 smallpad">
          <button
            type="button"
            class="btn btn-primary btn-block"
            id="add"
            (click)="add()"
            ref="text"
          >
            Append 1,000 rows
          </button>
        </div>
        <div class="col-sm-6 smallpad">
          <button
            type="button"
            class="btn btn-primary btn-block"
            id="update"
            (click)="update()"
          >
            Update every 10th row
          </button>
        </div>
        <div class="col-sm-6 smallpad">
          <button
            type="button"
            class="btn btn-primary btn-block"
            id="clear"
            (click)="clear()"
          >
            Clear
          </button>
        </div>
        <div class="col-sm-6 smallpad">
          <button
            type="button"
            class="btn btn-primary btn-block"
            id="swaprows"
            (click)="swapRows()"
          >
            Swap Rows
          </button>
        </div>
      </div>
    </div>
  </div>
  <table class="table table-hover table-striped test-data">
    <tbody>
      @for (item of data; track item.id) {
        <tr [class.danger]="item.id === selected">
          <td class="col-md-1">{{ item.id }}</td>
          <td class="col-md-4">
            <a href="#" (click)="select(item, $event)">{{ item.label }}</a>
          </td>
          <td class="col-md-1">
            <a href="#" (click)="delete(item, $event)"
              ><span
                class="glyphicon glyphicon-remove"
                aria-hidden="true"
              ></span
            ></a>
          </td>
          <td class="col-md-6"></td>
        </tr>
      }
    </tbody>
  </table>
  <span
    class="preloadicon glyphicon glyphicon-remove"
    aria-hidden="true"
  ></span>
</div>
